### ISSUE TITLE
Service node list should be sortable by name.

### ISSUE THREAD

**Issue by ianmacd** [konstantinullrich/oxen-service-node-operator#23]
It would be good if the app also allowed the user to sort the list of service nodes by name.

**Comment by necro-nemesis** [comment]
Just an observation but the sort order sequence appeared to be by when the node was added but on entering the 4th node out of 6 I entered it didn't follow that pattern any more. I don't think this is critical but my anticipated behavior was that I could drag the nodes up or down in the list to re-sequence them thereby putting whatever the user wanted to prioritize top down on the list.

**Comment by konstantinullrich** [comment]
The nodes are currently sorted by the last block they produced. So the node which expects to get the next reward is on top of this list.

But I'll add different ways to oder/sort your Nodes to the Settings

**Comment by necro-nemesis** [comment]
Oh. That would explain the observed behavior.
