### ISSUE TITLE
Remove node from monitoring option

### ISSUE THREAD

**Issue by necro-nemesis** [konstantinullrich/oxen-service-node-operator#52]
It may be there but I couldn't find a way to delete a node I was tracking. Just to give some appreciation of what I expected was either on the main screen to have the option available through long press on the node or more logically from the settings menu with a button to remove node monitoring once the node to be edited is selected there.

**Comment by konstantinullrich** [comment]
You can delete a node if you drag the settings entry of the Node you want to delete to the left.

![Screenshot_20220612-165451~2.png](https://user-images.githubusercontent.com/22809542/173239188-0c3467b0-abf7-44d6-b6f2-4a424f633253.png)

**Comment by necro-nemesis** [comment]
The problem is you made it too easy. I was searching for the hard way. ;) Thanks.
